service: example

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}

functions:
  your_lambda_fn:
    handler: your_lambda_fn.handler
plugins:
  - serverless-python-requirements
